# SPDX-License-Identifier: Apache-2.0
"""Overfit-100 integration golden: the full train loop memorizes a fixed slice (WP-040).

The Phase-5 end-to-end integration check. A single ``n``-scale
:class:`~lit_yolo.ptl.module.DetectionLitModule` is trained on a fixed ~100-image
synthetic detection slice (generated by ``fuse-augmentations``, R21/A26) with the
real training stack wired together — the dual-branch loss, the
:class:`~lit_yolo.optim.musgd.MuSGD` optimizer, the progressive-loss ramp, and the
``close_mosaic`` schedule (disabled from epoch 0 so the fit sees a stationary
target). If that loop composes correctly the network memorizes the slice, so the
one-to-one branch's decoded detections recall essentially every ground-truth box.

The gate is **train-set recall at IoU 0.5**: after training, each image is decoded
through the NMS-free :class:`~lit_yolo.decode.topk_e2e.TopKDecoder` and every
ground truth is greedily matched, in detection-score order (COCO-style, no
confidence gate), to a same-class detection whose IoU is at least
:data:`_IOU_THRESHOLD`. Recall is the matched fraction over all instances; the DoD
floor is ``>= 0.95``.

Golden policy (cross-platform, D-golden): the frozen ``goldens/gpu/overfit_micro_det.json``
pins the integer counts (images, instances, classes, epochs, image size) **exactly**
and the achieved recall with a generous tolerance (:data:`_RECALL_TOL`) — a
regression guard against a silent drop, while the ``>= 0.95`` floor (asserted by the
test and by :func:`main`) is the actual acceptance. The golden lives under
``goldens/gpu/`` so the default offline ``scripts/check_goldens.py`` run — which
globs only top-level and ``frozen/`` goldens — never recomputes it; it is checked
only under ``check_goldens.py --include-gpu`` on a machine with an accelerator.

The model recipe (variant, optimizer/loss gains, the progressive-loss endpoints,
seed, batch size) is read from ``configs/overfit_100.yaml`` so that file stays the
single source of truth. The image size (:data:`_IMG_SIZE`), the epoch budget
(:data:`_EPOCHS`, tuned above the recipe's documented 40 to clear the floor from
scratch), and the gradient clip (:data:`_GRAD_CLIP`, standing in for the deferred-A8
LR warmup) are this script's constants — all documented as proposed assumptions
(A-overfit-imgsz / A-overfit-epochs / A-overfit-clip).

Provenance: blueprint sec. 5.8-5.11, R1 Eq. 2-3. Assumptions: A8, A26.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

import torch
import yaml
from fuse_augmentations.data import generate_dataset  # type: ignore[import-untyped]
from fuse_augmentations.data.config import SplitRatios  # type: ignore[import-untyped]
from lightning.pytorch import Trainer, seed_everything
from torch import Tensor

from lit_yolo.assign import make_anchor_points
from lit_yolo.data.coco import CocoDetectionDataset
from lit_yolo.decode.topk_e2e import TopKDecoder
from lit_yolo.models.heads.detect import DualHeadOutput
from lit_yolo.models.registry import scale_spec
from lit_yolo.ptl.callbacks import CloseMosaicCallback
from lit_yolo.ptl.datamodule import DetectionDataModule
from lit_yolo.ptl.module import DetectionLitModule

#: Repository root (``scripts/`` is one level below it).
REPO_ROOT = Path(__file__).resolve().parents[1]

#: The recipe whose hyperparameters this run reuses (single source of truth).
_RECIPE_PATH = REPO_ROOT / "configs" / "overfit_100.yaml"

#: The frozen golden written by ``--freeze``; under ``gpu/`` so the offline harness skips it.
_GOLDEN_PATH = REPO_ROOT / "goldens" / "gpu" / "overfit_micro_det.json"

#: Producer spec recorded in the golden file (resolved by ``scripts/check_goldens.py``).
_PRODUCER_SPEC = "scripts.overfit_micro:overfit_micro_det"

#: Gitignored cache the synthetic slice is materialized into (never committed).
_SLICE_DIR = REPO_ROOT / ".cache" / "overfit_slice"

#: Number of images in the overfit slice (the "~100" of the WP name).
_NUM_IMAGES = 100

#: Seed for the ``fuse-augmentations`` slice generation (deterministic per A26).
_SLICE_SEED = 20260801

#: Square letterbox side for training and eval; 320 keeps the MPS run under ~15 min
#: while divisible by every stride (blueprint sec. 10 does not pin it — A-overfit-imgsz).
_IMG_SIZE = 320

#: Epoch budget, tuned above the recipe's documented 40: a from-scratch ``n``-scale
#: fit needs ~2.5k steps to drive one-to-one recall past the 0.95 floor at the fixed
#: LR (measured), and 100 epochs of the 100-image slice clears it with margin while
#: the MPS run stays well under ~15 min (A-overfit-epochs). ``close_mosaic`` tracks
#: this value so mosaic stays disabled from epoch 0 (the stationary-target recipe).
_EPOCHS = 100

#: Gradient-norm clip for the fit. The recipe defers the LR warmup (A8), so the
#: unbounded initial L1 gradient (the raw ltrb distances start large) otherwise
#: collapses the model to an all-background degenerate at the recipe LR; clipping is
#: the minimal stabilizer that lets the fixed LR overfit (A-overfit-clip).
_GRAD_CLIP = 10.0

#: Feature-level input-pixel strides of the P3/P4/P5 detection head.
_STRIDES: tuple[int, int, int] = (8, 16, 32)

#: Score floor dropping the fixed-size decoder's zero-score padding rows before
#: recall matching. Recall at IoU 0.5 is measured over the score-ranked detections
#: (COCO-style), not behind an arbitrary confidence gate.
_SCORE_FLOOR = 0.0

#: IoU at which a detection is deemed to recall a ground-truth box (the DoD's IoU 0.5).
_IOU_THRESHOLD = 0.5

#: Recall floor the overfit must clear (the WP-040 DoD).
_RECALL_FLOOR = 0.95

#: Golden tolerance on the achieved recall (integer counts are pinned exactly).
_RECALL_TOL = 0.04

#: Per-image detection cap used when decoding the one-to-one branch for recall.
_MAX_DET = 300

#: Task accepted by the CLI; segmentation/obb overfit goldens are later WPs.
_SUPPORTED_TASK = "det"


@dataclass(frozen=True)
class Recipe:
    """Hyperparameters read from ``configs/overfit_100.yaml`` for the overfit run.

    Attributes:
        variant: Scale letter selecting the compound-scaling multipliers.
        max_epochs: Training epoch budget.
        close_mosaic: Final-epoch mosaic-disable window (``>= max_epochs`` disables
            mosaic from epoch 0, the stationary-target recipe).
        seed: Global seed for reproducible weight init and data order.
        batch_size: Samples per batch.
        lr: MuSGD base learning rate.
        momentum: MuSGD momentum.
        weight_decay: MuSGD decoupled weight decay.
        box_gain: CIoU-term gain shared by both loss branches.
        cls_gain: Classification-term gain.
        l1_gain: L1-box-term gain.
        alpha_init: Progressive-loss one-to-many weight on the first epoch.
        alpha_final: Progressive-loss one-to-many weight on the last epoch.
    """

    variant: str
    max_epochs: int
    close_mosaic: int
    seed: int
    batch_size: int
    lr: float
    momentum: float
    weight_decay: float
    box_gain: float
    cls_gain: float
    l1_gain: float
    alpha_init: float
    alpha_final: float


def load_recipe(path: Path = _RECIPE_PATH) -> Recipe:
    """Load the overfit hyperparameters from the LightningCLI-style recipe YAML.

    Reads ``configs/overfit_100.yaml`` and lifts the model/optimizer/loss knobs, the
    ``variant``, ``seed`` and ``batch_size`` so that file stays the single source of
    truth for the model recipe. The placeholder ``data`` paths are ignored — the slice
    is generated fresh. The epoch budget is **not** taken from the config's documented
    ``40`` (insufficient for a from-scratch micro-overfit to the 0.95 floor): it is the
    tuned :data:`_EPOCHS`, and ``close_mosaic`` is set equal to it so mosaic stays off
    from epoch 0, exactly as the config's ``close_mosaic == max_epochs`` intends.

    Args:
        path: The recipe YAML path. Defaults to ``configs/overfit_100.yaml``.

    Returns:
        The parsed :class:`Recipe`.

    Examples:
        >>> recipe = load_recipe()
        >>> recipe.variant, recipe.max_epochs
        ('n', 100)
        >>> recipe.close_mosaic >= recipe.max_epochs  # mosaic off from epoch 0
        True
    """
    config = yaml.safe_load(path.read_text())
    model = config["model"]
    return Recipe(
        variant=str(config["variant"]),
        max_epochs=_EPOCHS,
        close_mosaic=_EPOCHS,
        seed=int(config["seed_everything"]),
        batch_size=int(config["data"]["batch_size"]),
        lr=float(model["lr"]),
        momentum=float(model["momentum"]),
        weight_decay=float(model["weight_decay"]),
        box_gain=float(model["box_gain"]),
        cls_gain=float(model["cls_gain"]),
        l1_gain=float(model["l1_gain"]),
        alpha_init=float(model["alpha_init"]),
        alpha_final=float(model["alpha_final"]),
    )


def generate_slice(slice_dir: Path = _SLICE_DIR) -> Path:
    """Materialize the fixed ~100-image synthetic detection slice under ``slice_dir``.

    Uses ``fuse-augmentations`` with ``task="segmentation"`` so every annotation
    carries a polygon ring (the reader keeps only polygon instances), giving a
    seeded, byte-reproducible slice (A26). Idempotent: an existing slice with its
    annotation file is reused rather than regenerated.

    Args:
        slice_dir: Parent directory the ``train`` split is written into. Defaults to
            the gitignored ``.cache/overfit_slice``.

    Returns:
        The ``train`` split directory (holds the images and ``_annotations.coco.json``).

    Examples:
        >>> split = generate_slice()  # doctest: +SKIP
        >>> (split / "_annotations.coco.json").is_file()  # doctest: +SKIP
        True
    """

    split = slice_dir / "train"
    annotation = split / "_annotations.coco.json"
    if not annotation.is_file():
        generate_dataset(
            slice_dir,
            num_images=_NUM_IMAGES,
            fmt="coco",
            task="segmentation",
            class_mode="shape",
            split_ratios=SplitRatios(train=1.0, val=0.0, test=0.0),
            seed=_SLICE_SEED,
            img_size=128,
        )
    return split


def _num_classes(split: Path) -> int:
    """Return the contiguous class count of the slice's annotation file."""
    dataset = CocoDetectionDataset(split, split / "_annotations.coco.json")
    return len(dataset.category_id_to_label)


def build_datamodule(split: Path, recipe: Recipe) -> DetectionDataModule:
    """Build a datamodule pointing both splits at the single overfit slice.

    Args:
        split: The slice's ``train`` split directory.
        recipe: The parsed recipe (supplies ``variant``, ``batch_size``, ``seed``).

    Returns:
        A :class:`~lit_yolo.ptl.datamodule.DetectionDataModule` with ``num_workers=0``
        (byte-deterministic epochs) whose train and val loaders read the same slice.

    Examples:
        >>> dm = build_datamodule(generate_slice(), load_recipe())  # doctest: +SKIP
        >>> dm.setup("fit")  # doctest: +SKIP
    """
    annotation = split / "_annotations.coco.json"
    return DetectionDataModule(
        data_root=split,
        batch_size=recipe.batch_size,
        num_workers=0,
        variant=recipe.variant,
        img_size=_IMG_SIZE,
        train_images_dir=split,
        train_ann_file=annotation,
        val_images_dir=split,
        val_ann_file=annotation,
        seed=recipe.seed,
    )


def build_module(recipe: Recipe, num_classes: int) -> DetectionLitModule:
    """Build the ``n``-scale detection module from the recipe hyperparameters.

    Args:
        recipe: The parsed recipe supplying the scale letter and every optimizer /
            loss / progressive-loss knob.
        num_classes: Class count of the slice (derived from its annotations).

    Returns:
        A :class:`~lit_yolo.ptl.module.DetectionLitModule` at the recipe's scale.

    Examples:
        >>> module = build_module(load_recipe(), num_classes=4)
        >>> module.head.num_classes
        4
    """
    spec = scale_spec(recipe.variant)
    return DetectionLitModule(
        depth=spec.depth,
        width=spec.width,
        max_channels=spec.max_channels,
        num_classes=num_classes,
        lr=recipe.lr,
        momentum=recipe.momentum,
        weight_decay=recipe.weight_decay,
        box_gain=recipe.box_gain,
        cls_gain=recipe.cls_gain,
        l1_gain=recipe.l1_gain,
        alpha=recipe.alpha_init,
        alpha_init=recipe.alpha_init,
        alpha_final=recipe.alpha_final,
    )


def _make_trainer(recipe: Recipe, deterministic: bool) -> Trainer:
    """Build the overfit trainer: mosaic off from epoch 0, gradients norm-clipped."""
    return Trainer(
        max_epochs=recipe.max_epochs,
        accelerator="auto",
        deterministic=deterministic,
        gradient_clip_val=_GRAD_CLIP,
        num_sanity_val_steps=0,
        limit_val_batches=0,
        logger=False,
        enable_checkpointing=False,
        enable_progress_bar=False,
        callbacks=[CloseMosaicCallback(close_mosaic=recipe.close_mosaic)],
    )


def _box_iou(boxes_a: Tensor, boxes_b: Tensor) -> Tensor:
    """Pairwise IoU between two ``xyxy`` box sets.

    Args:
        boxes_a: ``(M, 4)`` boxes in ``xyxy``.
        boxes_b: ``(N, 4)`` boxes in ``xyxy``.

    Returns:
        An ``(M, N)`` IoU matrix (zeros when either set is empty).

    Examples:
        >>> import torch
        >>> a = torch.tensor([[0.0, 0.0, 2.0, 2.0]])
        >>> b = torch.tensor([[0.0, 0.0, 2.0, 2.0], [2.0, 2.0, 4.0, 4.0]])
        >>> _box_iou(a, b).tolist()
        [[1.0, 0.0]]
    """
    if boxes_a.numel() == 0 or boxes_b.numel() == 0:
        return boxes_a.new_zeros((boxes_a.shape[0], boxes_b.shape[0]))
    area_a = (boxes_a[:, 2] - boxes_a[:, 0]).clamp(min=0) * (boxes_a[:, 3] - boxes_a[:, 1]).clamp(min=0)
    area_b = (boxes_b[:, 2] - boxes_b[:, 0]).clamp(min=0) * (boxes_b[:, 3] - boxes_b[:, 1]).clamp(min=0)
    top_left = torch.max(boxes_a[:, None, :2], boxes_b[None, :, :2])
    bottom_right = torch.min(boxes_a[:, None, 2:], boxes_b[None, :, 2:])
    wh = (bottom_right - top_left).clamp(min=0)
    intersection = wh[..., 0] * wh[..., 1]
    union = area_a[:, None] + area_b[None, :] - intersection
    return intersection / union.clamp(min=1e-9)


def _recall_counts(dets: Tensor, gt_boxes: Tensor, gt_labels: Tensor) -> tuple[int, int]:
    """Score-ordered greedy matching of one image's detections to its ground truths.

    The COCO-style recall match: detections are taken in descending score order
    (the fixed-size decoder already sorts them, with the zero-score padding rows
    dropped by :data:`_SCORE_FLOOR`) and each claims, at most once, the highest-IoU
    still-unmatched ground truth of its own class whose IoU clears
    :data:`_IOU_THRESHOLD`. Processing high-score detections first lets the confident
    correct boxes claim their ground truths before any weak box can.

    Args:
        dets: ``(N, 6)`` A9 detections ``[x1, y1, x2, y2, score, class]`` for one
            image, sorted by descending score.
        gt_boxes: ``(G, 4)`` ground-truth ``xyxy`` boxes.
        gt_labels: ``(G,)`` ground-truth class ids.

    Returns:
        A ``(matched, total)`` pair: matched ground truths and total ground truths.

    Examples:
        >>> import torch
        >>> dets = torch.tensor([[0.0, 0.0, 2.0, 2.0, 0.9, 1.0]])
        >>> gt_boxes = torch.tensor([[0.0, 0.0, 2.0, 2.0]])
        >>> _recall_counts(dets, gt_boxes, torch.tensor([1]))
        (1, 1)
    """
    total = int(gt_boxes.shape[0])
    if total == 0:
        return 0, 0
    keep = dets[dets[:, 4] > _SCORE_FLOOR]
    iou = _box_iou(keep[:, :4], gt_boxes)  # (P, G)
    matched_gt = torch.zeros(total, dtype=torch.bool)
    matched = 0
    for det_index in range(keep.shape[0]):
        available = (keep[det_index, 5] == gt_labels) & ~matched_gt & (iou[det_index] >= _IOU_THRESHOLD)
        if bool(available.any()):
            matched_gt[int((iou[det_index] * available).argmax())] = True
            matched += 1
            if matched == total:
                break
    return matched, total


def _anchor_grid(device: torch.device) -> tuple[Tensor, Tensor]:
    """Return the ``(anchor_points, strides)`` grid for the fixed image size on ``device``."""
    feature_sizes = [(_IMG_SIZE // stride, _IMG_SIZE // stride) for stride in _STRIDES]
    points, strides = make_anchor_points(feature_sizes, list(_STRIDES))
    return points.to(device), strides.to(device)


def evaluate_recall(module: DetectionLitModule, datamodule: DetectionDataModule) -> tuple[float, int]:
    """Measure train-set recall at IoU 0.5 over the letterbox-only slice.

    Runs the trained module over the val loader (the same 100 images with only the
    letterbox transform — no augmentation), decodes the one-to-one branch through
    the NMS-free :class:`~lit_yolo.decode.topk_e2e.TopKDecoder`, and greedily matches
    every ground truth to a same-class detection (see :func:`_recall_counts`).

    Args:
        module: The trained detection module.
        datamodule: The datamodule whose val loader yields the letterboxed slice.

    Returns:
        A ``(recall, total_instances)`` pair: the matched fraction over all ground
        truths and the total ground-truth count.

    Examples:
        >>> evaluate_recall(module, datamodule)  # doctest: +SKIP
        (1.0, 592)
    """
    device = module.device
    module.eval()
    decoder = TopKDecoder(k=_MAX_DET)
    anchor_points, strides = _anchor_grid(device)
    matched_total = 0
    instance_total = 0
    with torch.no_grad():
        for images, targets in datamodule.val_dataloader():
            head_out: DualHeadOutput = module(images.to(device))
            dets = decoder(head_out.o2o_cls, head_out.o2o_box, anchor_points, strides).cpu()
            for image_dets, target in zip(dets, targets, strict=True):
                matched, total = _recall_counts(image_dets, target.boxes, target.labels)
                matched_total += matched
                instance_total += total
    recall = matched_total / instance_total if instance_total else 0.0
    return recall, instance_total


def _train_and_score(recipe: Recipe, split: Path, deterministic: bool) -> tuple[float, int, int]:
    """Build, train, and score one overfit run; return ``(recall, instances, classes)``."""
    seed_everything(recipe.seed, workers=True)
    num_classes = _num_classes(split)
    module = build_module(recipe, num_classes)
    datamodule = build_datamodule(split, recipe)
    _make_trainer(recipe, deterministic).fit(module, datamodule=datamodule)
    recall, instances = evaluate_recall(module, datamodule)
    return recall, instances, num_classes


def run_overfit() -> dict[str, float]:
    """Run the full overfit pipeline and return the golden metric mapping.

    Generates the slice, trains the ``n``-scale module end to end (attempting
    deterministic execution, falling back to non-deterministic if the accelerator
    lacks a deterministic kernel — expected on MPS), then measures train-set recall
    at IoU 0.5. Every value is produced by *running* the pipeline, never hand-written.

    Returns:
        A mapping of the frozen metrics: ``num_images``, ``num_instances``,
        ``num_classes``, ``epochs``, ``img_size`` (all integer-valued) and
        ``train_recall_at_050``.

    Examples:
        >>> metrics = run_overfit()  # doctest: +SKIP
        >>> metrics["train_recall_at_050"] >= 0.95  # doctest: +SKIP
        True
    """
    recipe = load_recipe()
    split = generate_slice()
    try:
        recall, instances, num_classes = _train_and_score(recipe, split, deterministic=True)
    except RuntimeError:
        recall, instances, num_classes = _train_and_score(recipe, split, deterministic=False)
    return {
        "num_images": float(_NUM_IMAGES),
        "num_instances": float(instances),
        "num_classes": float(num_classes),
        "epochs": float(recipe.max_epochs),
        "img_size": float(_IMG_SIZE),
        "train_recall_at_050": round(recall, 6),
    }


def overfit_micro_det() -> dict[str, float]:
    """Golden producer: the overfit-100 detection metrics (WP-040).

    A zero-argument producer for the golden harness. Recomputing it retrains the
    slice from scratch on the local accelerator, so it is excluded from the default
    offline harness (the golden lives under ``goldens/gpu/``) and checked only under
    ``scripts/check_goldens.py --include-gpu``.

    Returns:
        The metric mapping from :func:`run_overfit`.

    Examples:
        >>> metrics = overfit_micro_det()  # doctest: +SKIP
        >>> sorted(metrics)  # doctest: +SKIP
        ['epochs', 'img_size', 'num_classes', 'num_images', 'num_instances', 'train_recall_at_050']
    """
    return run_overfit()


def write_golden(metrics: dict[str, float], path: Path = _GOLDEN_PATH) -> None:
    """Freeze ``metrics`` into the golden JSON with the recall tolerance pinned.

    Args:
        metrics: The metric mapping to store as the golden's ``values``.
        path: The golden file path. Defaults to ``goldens/gpu/overfit_micro_det.json``.

    Examples:
        >>> write_golden(run_overfit())  # doctest: +SKIP
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    golden = {
        "producer": _PRODUCER_SPEC,
        "tolerances": {"train_recall_at_050": _RECALL_TOL},
        "values": metrics,
    }
    path.write_text(json.dumps(golden, indent=2) + "\n")


def main(argv: list[str] | None = None) -> int:
    """Run the overfit gate and optionally freeze the golden.

    Args:
        argv: Command-line arguments (defaults to ``sys.argv[1:]``).

    Returns:
        ``0`` when recall clears the ``>= 0.95`` floor; ``1`` otherwise (or when an
        unsupported task is requested).
    """
    parser = argparse.ArgumentParser(description="Overfit a fixed ~100-image slice and gate on train recall.")
    parser.add_argument("--task", default=_SUPPORTED_TASK, help="detection task (only 'det' is wired for WP-040)")
    parser.add_argument("--freeze", action="store_true", help="write goldens/gpu/overfit_micro_det.json on success")
    args = parser.parse_args(argv)

    if args.task != _SUPPORTED_TASK:
        print(f"unsupported task {args.task!r}; only {_SUPPORTED_TASK!r} is wired for WP-040")
        return 1

    metrics = run_overfit()
    recall = metrics["train_recall_at_050"]
    print(f"overfit-{args.task}: recall@0.5 = {recall:.4f} over {int(metrics['num_instances'])} instances")
    if recall < _RECALL_FLOOR:
        print(f"FAIL: recall {recall:.4f} below floor {_RECALL_FLOOR}")
        return 1
    if args.freeze:
        write_golden(metrics)
        print(f"froze golden -> {_GOLDEN_PATH.relative_to(REPO_ROOT)}")
    print(f"PASS: recall {recall:.4f} >= {_RECALL_FLOOR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
