# SPDX-License-Identifier: Apache-2.0
"""Overfit-100 integration golden: the full train loop memorizes a fixed slice (WP-040).

The Phase-5 end-to-end integration check. A single ``n``-scale
:class:`~lucid_yolo.ptl.module.DetectionLitModule` is trained on a fixed ~100-image
synthetic detection slice (generated by ``fuse-augmentations``, R21/A26) with the
real training stack wired together — the dual-branch loss, the
:class:`~lucid_yolo.optim.musgd.MuSGD` optimizer, the progressive-loss ramp, and the
``close_mosaic`` schedule (disabled from epoch 0 so the fit sees a stationary
target). If that loop composes correctly the network memorizes the slice, so the
one-to-one branch's decoded detections recall essentially every ground-truth box.

The gate is **train-set recall at IoU 0.5**: after training, each image is decoded
through the NMS-free :class:`~lucid_yolo.decode.topk_e2e.TopKDecoder` and every
ground truth is greedily matched, in detection-score order (COCO-style, no
confidence gate), to a same-class detection whose IoU is at least
:data:`_IOU_THRESHOLD`. Recall is the matched fraction over all instances; the DoD
floor is ``>= 0.95``.

Golden policy (cross-platform, D-golden): the frozen ``goldens/gpu/overfit_micro_det.json``
pins the integer counts (images, instances, classes, epochs, image size) **exactly**
and the achieved recall with a generous tolerance (:data:`_RECALL_TOL`) — a
regression guard against a silent drop, while the ``>= 0.95`` floor (asserted by the
test and by :func:`main`) is the actual acceptance. The golden lives under
``goldens/gpu/`` so the default offline ``scripts/check_goldens.py`` run — which
globs only top-level and ``frozen/`` goldens — never recomputes it; it is checked
only under ``check_goldens.py --include-gpu`` on a machine with an accelerator.

The model recipe (variant, optimizer/loss gains, the progressive-loss endpoints,
seed, batch size) is read from ``lucid_yolo/configs/overfit_100.yaml`` so that file stays the
single source of truth. The image size (:data:`_IMG_SIZE`), the epoch budget
(:data:`_EPOCHS`, tuned above the recipe's documented 40 to clear the floor from
scratch), and the gradient clip (:data:`_GRAD_CLIP`, standing in for the deferred-A8
LR warmup) are this script's constants — all documented as proposed assumptions
(A-overfit-imgsz / A-overfit-epochs / A-overfit-clip).

Segmentation (``--task seg``, WP-087):
    The same loop with ``task="segment"``, gated on **train mask IoU** instead of
    recall. Each image is decoded through the deployed segmentation path — the
    one-to-one branch's boxes and coefficients paired by
    :func:`~lucid_yolo.models.heads.detect.o2o_topk_with_indices`, assembled and
    cropped by :func:`~lucid_yolo.eval.segment_decode.decode_instance_masks` — and
    every ground truth is matched to a detection by the *same* greedy box rule the
    recall gate uses (:func:`_match_pairs`, written once). The score is the mean
    mask IoU over **all** instances, so an unmatched ground truth contributes a
    zero rather than being excused; the floor is :data:`_MASK_IOU_FLOOR`.

    This is the fast wiring check for the whole segmentation training path: mask
    targets on the wrong grid, coefficients paired with the wrong anchor, or an
    unsupervised one-to-one coefficient stem all show up here in minutes instead
    of after a COCO run.

Oriented detection (``--task obb``, WP-088):
    The same loop with ``task="obb"``, gated on the **train rotated mAP50** of the
    WP-063 protocol. The slice is generated with ``fuse-augmentations``' own ``obb``
    task, which writes each object's rotated box as a four-corner ``segmentation``
    ring, and is read through the loader's oriented mode — so what this gate measures
    is the loader, the assignment, the rotated objective, the decode and the metric in
    one line, rather than any of them in isolation (the Phase 8 defect was that every
    one of them was correct alone).

    It uses its own slice directory. Sharing the segmentation slice would silently
    score oriented training against annotations whose rings are not quadrilaterals,
    and the first symptom would be a number rather than an error.

    ``[DATA]`` note: DOTA is the tier dataset for this task, and the synthetic
    rotated scenes are its A26-sanctioned development stand-in — this gate is a
    wiring check, never a claim about DOTA.

Provenance: blueprint sec. 5.8-5.11, R1 Eq. 2-3. Assumptions: A8, A26, A38, A49, A50.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import torch
import yaml
from fuse_augmentations.data import generate_dataset  # type: ignore[import-untyped]
from fuse_augmentations.data.config import SplitRatios  # type: ignore[import-untyped]
from pytorch_lightning import Trainer, seed_everything
from torch import Tensor

import lucid_yolo
from lucid_yolo.assign import make_anchor_points
from lucid_yolo.data.coco import CocoDetectionDataset
from lucid_yolo.data.rasterize import rasterize_polygons
from lucid_yolo.data.targets import Targets
from lucid_yolo.decode.topk_e2e import TopKDecoder
from lucid_yolo.eval.dota_eval import (
    MAX_DETECTIONS,
    evaluate_rotated_map,
    rotated_detections_to_predictions,
)
from lucid_yolo.eval.segment_decode import decode_instance_masks
from lucid_yolo.models.heads.detect import DualHeadOutput, decode_ltrb, o2o_topk_with_indices
from lucid_yolo.models.heads.obb import decode_rboxes, o2o_rotated_topk
from lucid_yolo.models.registry import scale_spec
from lucid_yolo.ptl.callbacks import CloseMosaicCallback
from lucid_yolo.ptl.datamodule import DetectionDataModule
from lucid_yolo.ptl.module import DetectionLitModule

#: Repository root (``scripts/`` is one level below it).
REPO_ROOT = Path(__file__).resolve().parents[1]

#: The recipe whose hyperparameters this run reuses (single source of truth);
#: read from the packaged configs tree (``lucid_yolo/configs``).
_RECIPE_PATH = Path(lucid_yolo.__file__).resolve().parent / "configs" / "overfit_100.yaml"

#: The frozen golden written by ``--freeze``; under ``gpu/`` so the offline harness skips it.
_GOLDEN_PATH = REPO_ROOT / "goldens" / "gpu" / "overfit_micro_det.json"

#: The segmentation counterpart of :data:`_GOLDEN_PATH` (WP-087).
_SEG_GOLDEN_PATH = REPO_ROOT / "goldens" / "gpu" / "overfit_micro_seg.json"

#: Producer spec recorded in the golden file (resolved by ``scripts/check_goldens.py``).
_PRODUCER_SPEC = "scripts.overfit_micro:overfit_micro_det"

#: Producer spec of the segmentation golden.
_SEG_PRODUCER_SPEC = "scripts.overfit_micro:overfit_micro_seg"

#: Gitignored cache the synthetic slice is materialized into (never committed).
_SLICE_DIR = REPO_ROOT / ".cache" / "overfit_slice"

#: The oriented gate's own slice (WP-088). Deliberately not the one above: that slice's
#: rings are many-vertex segmentation polygons, which the oriented reader rejects, and a
#: shared directory would make "which slice is cached here" depend on run order.
_OBB_SLICE_DIR = REPO_ROOT / ".cache" / "overfit_slice_obb"

#: The oriented golden, the third of the accelerator-only set.
_OBB_GOLDEN_PATH = REPO_ROOT / "goldens" / "gpu" / "overfit_micro_obb.json"

#: Producer spec of the oriented golden.
_OBB_PRODUCER_SPEC = "scripts.overfit_micro:overfit_micro_obb"

#: Train rotated mAP50 the oriented overfit must clear (the WP-088 DoD).
_ROTATED_MAP50_FLOOR = 0.9

#: Golden tolerance on the achieved rotated mAP50 (integer counts are pinned exactly).
_ROTATED_MAP50_TOL = 0.05

#: Number of images in the overfit slice (the "~100" of the WP name).
_NUM_IMAGES = 100

#: Seed for the ``fuse-augmentations`` slice generation (deterministic per A26).
_SLICE_SEED = 20260801

#: Square letterbox side for training and eval; 320 keeps the MPS run under ~15 min
#: while divisible by every stride (blueprint sec. 10 does not pin it — A-overfit-imgsz).
_IMG_SIZE = 320

#: Epoch budget, tuned above the recipe's documented 40: a from-scratch ``n``-scale
#: fit needs ~2.5k steps to drive one-to-one recall past the 0.95 floor at the fixed
#: LR (measured), and 100 epochs of the 100-image slice clears it with margin while
#: the MPS run stays well under ~15 min (A-overfit-epochs). ``close_mosaic`` tracks
#: this value so mosaic stays disabled from epoch 0 (the stationary-target recipe).
_EPOCHS = 100

#: Gradient-norm clip for the fit. The recipe defers the LR warmup (A8), so the
#: unbounded initial L1 gradient (the raw ltrb distances start large) otherwise
#: collapses the model to an all-background degenerate at the recipe LR; clipping is
#: the minimal stabilizer that lets the fixed LR overfit (A-overfit-clip).
_GRAD_CLIP = 10.0

#: Feature-level input-pixel strides of the P3/P4/P5 detection head.
_STRIDES: tuple[int, int, int] = (8, 16, 32)

#: Score floor dropping the fixed-size decoder's zero-score padding rows before
#: recall matching. Recall at IoU 0.5 is measured over the score-ranked detections
#: (COCO-style), not behind an arbitrary confidence gate.
_SCORE_FLOOR = 0.0

#: IoU at which a detection is deemed to recall a ground-truth box (the DoD's IoU 0.5).
_IOU_THRESHOLD = 0.5

#: Recall floor the overfit must clear (the WP-040 DoD).
_RECALL_FLOOR = 0.95

#: Golden tolerance on the achieved recall (integer counts are pinned exactly).
_RECALL_TOL = 0.04

#: Per-image detection cap used when decoding the one-to-one branch for recall.
_MAX_DET = 300

#: Per-image detection cap when decoding *masks*. Lower than :data:`_MAX_DET` because
#: every kept detection materializes a full-canvas float mask during decode; the slice
#: carries a handful of instances per image, so the score-ranked head of the list is
#: all the greedy matching can ever consume.
_SEG_MAX_DET = 50

#: Mean train mask IoU the segmentation overfit must clear (the WP-087 DoD).
_MASK_IOU_FLOOR = 0.7

#: Golden tolerance on the achieved mask IoU (integer counts are pinned exactly).
_MASK_IOU_TOL = 0.05

#: Mask-decode probability floor; the A37 default, restated here only to be explicit.
_MASK_THRESHOLD = 0.5

#: Leading columns of the A9 detection tuple holding the ``xyxy`` box.
_BOX_COLUMNS = 4


@dataclass(frozen=True)
class Recipe:
    """Hyperparameters read from ``lucid_yolo/configs/overfit_100.yaml`` for the overfit run.

    Attributes:
        variant: Scale letter selecting the compound-scaling multipliers.
        max_epochs: Training epoch budget.
        close_mosaic: Final-epoch mosaic-disable window (``>= max_epochs`` disables
            mosaic from epoch 0, the stationary-target recipe).
        seed: Global seed for reproducible weight init and data order.
        batch_size: Samples per batch.
        lr: MuSGD base learning rate.
        momentum: MuSGD momentum.
        weight_decay: MuSGD decoupled weight decay.
        box_gain: CIoU-term gain shared by both loss branches.
        cls_gain: Classification-term gain.
        l1_gain: L1-box-term gain.
        alpha_init: Progressive-loss one-to-many weight on the first epoch.
        alpha_final: Progressive-loss one-to-many weight on the last epoch.
    """

    variant: str
    max_epochs: int
    close_mosaic: int
    seed: int
    batch_size: int
    lr: float
    momentum: float
    weight_decay: float
    box_gain: float
    cls_gain: float
    l1_gain: float
    alpha_init: float
    alpha_final: float


def load_recipe(path: Path = _RECIPE_PATH) -> Recipe:
    """Load the overfit hyperparameters from the LightningCLI-style recipe YAML.

    Reads ``lucid_yolo/configs/overfit_100.yaml`` and lifts the model/optimizer/loss knobs, the
    ``variant``, ``seed`` and ``batch_size`` so that file stays the single source of
    truth for the model recipe. The placeholder ``data`` paths are ignored — the slice
    is generated fresh. The epoch budget is **not** taken from the config's documented
    ``40`` (insufficient for a from-scratch micro-overfit to the 0.95 floor): it is the
    tuned :data:`_EPOCHS`, and ``close_mosaic`` is set equal to it so mosaic stays off
    from epoch 0, exactly as the config's ``close_mosaic == max_epochs`` intends.

    Args:
        path: The recipe YAML path. Defaults to ``lucid_yolo/configs/overfit_100.yaml``.

    Returns:
        The parsed :class:`Recipe`.

    Examples:
        >>> recipe = load_recipe()
        >>> recipe.variant, recipe.max_epochs
        ('n', 100)
        >>> recipe.close_mosaic >= recipe.max_epochs  # mosaic off from epoch 0
        True
    """
    config = yaml.safe_load(path.read_text())
    model = config["model"]
    return Recipe(
        variant=str(config["variant"]),
        max_epochs=_EPOCHS,
        close_mosaic=_EPOCHS,
        seed=int(config["seed_everything"]),
        batch_size=int(config["data"]["batch_size"]),
        lr=float(model["lr"]),
        momentum=float(model["momentum"]),
        weight_decay=float(model["weight_decay"]),
        box_gain=float(model["box_gain"]),
        cls_gain=float(model["cls_gain"]),
        l1_gain=float(model["l1_gain"]),
        alpha_init=float(model["alpha_init"]),
        alpha_final=float(model["alpha_final"]),
    )


def generate_slice(slice_dir: Path = _SLICE_DIR, generator_task: str = "segmentation") -> Path:
    """Materialize the fixed ~100-image synthetic slice under ``slice_dir``.

    Uses ``fuse-augmentations`` with ``task="segmentation"`` so every annotation
    carries a polygon ring (the reader keeps only polygon instances), giving a
    seeded, byte-reproducible slice (A26). ``generator_task="obb"`` writes the same
    scenes with each object's rotated box as a four-corner ring instead, which is
    what the oriented reader fits its long-edge boxes to. Idempotent: an existing
    slice with its annotation file is reused rather than regenerated.

    Args:
        slice_dir: Parent directory the ``train`` split is written into. Defaults to
            the gitignored ``.cache/overfit_slice``.
        generator_task: The ``fuse-augmentations`` task, ``"segmentation"`` (the
            default, used by the detection and mask gates) or ``"obb"``.

    Returns:
        The ``train`` split directory (holds the images and ``_annotations.coco.json``).

    Examples:
        >>> split = generate_slice()  # doctest: +SKIP
        >>> (split / "_annotations.coco.json").is_file()  # doctest: +SKIP
        True
    """

    split = slice_dir / "train"
    annotation = split / "_annotations.coco.json"
    if not annotation.is_file():
        generate_dataset(
            slice_dir,
            num_images=_NUM_IMAGES,
            fmt="coco",
            task=generator_task,
            class_mode="shape",
            split_ratios=SplitRatios(train=1.0, val=0.0, test=0.0),
            seed=_SLICE_SEED,
            img_size=128,
        )
    return split


def _num_classes(split: Path) -> int:
    """Return the contiguous class count of the slice's annotation file."""
    dataset = CocoDetectionDataset(split, split / "_annotations.coco.json")
    return len(dataset.category_id_to_label)


def build_datamodule(
    split: Path, recipe: Recipe, *, mask_targets: bool = False, rotated_targets: bool = False
) -> DetectionDataModule:
    """Build a datamodule pointing both splits at the single overfit slice.

    Args:
        split: The slice's ``train`` split directory.
        recipe: The parsed recipe (supplies ``variant``, ``batch_size``, ``seed``).
        mask_targets: Rasterise the instance masks in the loader, as a segmentation
            training run does. Set for the ``seg`` gate so the frozen mask IoU covers
            the loader-side path the real runs take, not only the in-step fallback.
        rotated_targets: Read each annotation's four-corner ring as a rotated box, as
            an oriented training run does. Set for the ``obb`` gate, for the same
            reason: the gate is meant to cover the loader, not to bypass it.

    Returns:
        A :class:`~lucid_yolo.ptl.datamodule.DetectionDataModule` with ``num_workers=0``
        (byte-deterministic epochs) whose train and val loaders read the same slice.

    Examples:
        >>> dm = build_datamodule(generate_slice(), load_recipe())  # doctest: +SKIP
        >>> dm.setup("fit")  # doctest: +SKIP
    """
    annotation = split / "_annotations.coco.json"
    return DetectionDataModule(
        data_root=split,
        batch_size=recipe.batch_size,
        num_workers=0,
        variant=recipe.variant,
        img_size=_IMG_SIZE,
        train_images_dir=split,
        train_ann_file=annotation,
        val_images_dir=split,
        val_ann_file=annotation,
        seed=recipe.seed,
        mask_targets=mask_targets,
        rotated_targets=rotated_targets,
    )


def build_module(recipe: Recipe, num_classes: int, module_task: str = "detect") -> DetectionLitModule:
    """Build the ``n``-scale module from the recipe hyperparameters.

    Args:
        recipe: The parsed recipe supplying the scale letter and every optimizer /
            loss / progressive-loss knob.
        num_classes: Class count of the slice (derived from its annotations).
        module_task: The module's supervision task — ``"detect"`` (the WP-040
            gate) or ``"segment"`` (the WP-087 gate, which additionally builds and
            supervises the mask branches at the module's A38 default gains).

    Returns:
        A :class:`~lucid_yolo.ptl.module.DetectionLitModule` at the recipe's scale.

    Examples:
        >>> module = build_module(load_recipe(), num_classes=4)
        >>> module.head.num_classes
        4
        >>> build_module(load_recipe(), num_classes=4, module_task="segment").protonet.num_prototypes
        32
    """
    spec = scale_spec(recipe.variant)
    return DetectionLitModule(
        depth=spec.depth,
        width=spec.width,
        max_channels=spec.max_channels,
        num_classes=num_classes,
        task=module_task,
        lr=recipe.lr,
        # A8 schedule off (lrf >= 1, no warmup): the overfit golden memorizes at a
        # constant LR and its trajectory was frozen before WP-072 landed.
        lrf=1.0,
        warmup_epochs=0.0,
        momentum=recipe.momentum,
        weight_decay=recipe.weight_decay,
        box_gain=recipe.box_gain,
        cls_gain=recipe.cls_gain,
        l1_gain=recipe.l1_gain,
        alpha=recipe.alpha_init,
        alpha_init=recipe.alpha_init,
        alpha_final=recipe.alpha_final,
    )


def _make_trainer(recipe: Recipe, deterministic: bool) -> Trainer:
    """Build the overfit trainer: mosaic off from epoch 0, gradients norm-clipped."""
    return Trainer(
        max_epochs=recipe.max_epochs,
        accelerator="auto",
        deterministic=deterministic,
        gradient_clip_val=_GRAD_CLIP,
        num_sanity_val_steps=0,
        limit_val_batches=0,
        logger=False,
        enable_checkpointing=False,
        enable_progress_bar=False,
        callbacks=[CloseMosaicCallback(close_mosaic=recipe.close_mosaic)],
    )


def _box_iou(boxes_a: Tensor, boxes_b: Tensor) -> Tensor:
    """Pairwise IoU between two ``xyxy`` box sets.

    Args:
        boxes_a: ``(M, 4)`` boxes in ``xyxy``.
        boxes_b: ``(N, 4)`` boxes in ``xyxy``.

    Returns:
        An ``(M, N)`` IoU matrix (zeros when either set is empty).

    Examples:
        >>> import torch
        >>> a = torch.tensor([[0.0, 0.0, 2.0, 2.0]])
        >>> b = torch.tensor([[0.0, 0.0, 2.0, 2.0], [2.0, 2.0, 4.0, 4.0]])
        >>> _box_iou(a, b).tolist()
        [[1.0, 0.0]]
    """
    if boxes_a.numel() == 0 or boxes_b.numel() == 0:
        return boxes_a.new_zeros((boxes_a.shape[0], boxes_b.shape[0]))
    area_a = (boxes_a[:, 2] - boxes_a[:, 0]).clamp(min=0) * (boxes_a[:, 3] - boxes_a[:, 1]).clamp(min=0)
    area_b = (boxes_b[:, 2] - boxes_b[:, 0]).clamp(min=0) * (boxes_b[:, 3] - boxes_b[:, 1]).clamp(min=0)
    top_left = torch.max(boxes_a[:, None, :2], boxes_b[None, :, :2])
    bottom_right = torch.min(boxes_a[:, None, 2:], boxes_b[None, :, 2:])
    wh = (bottom_right - top_left).clamp(min=0)
    intersection = wh[..., 0] * wh[..., 1]
    union = area_a[:, None] + area_b[None, :] - intersection
    return intersection / union.clamp(min=1e-9)


def _match_pairs(dets: Tensor, gt_boxes: Tensor, gt_labels: Tensor) -> list[tuple[int, int]]:
    """Score-ordered greedy matching of one image's detections to its ground truths.

    The COCO-style recall match, and the **only** implementation of it: detections
    are taken in descending score order (the fixed-size decoder already sorts them,
    with the zero-score padding rows dropped by :data:`_SCORE_FLOOR`) and each
    claims, at most once, the highest-IoU still-unmatched ground truth of its own
    class whose IoU clears :data:`_IOU_THRESHOLD`. Processing high-score detections
    first lets the confident correct boxes claim their ground truths before any weak
    box can.

    Both gates consume it — :func:`_recall_counts` needs only how many matched, the
    mask gate needs *which* detection matched each ground truth — so it returns the
    pairs and the counting is a one-line wrapper. A separate matcher for the mask
    gate would be free to drift into scoring masks against a different pairing than
    the recall it is compared with.

    Args:
        dets: ``(N, 6)`` A9 detections ``[x1, y1, x2, y2, score, class]`` for one
            image, sorted by descending score.
        gt_boxes: ``(G, 4)`` ground-truth ``xyxy`` boxes.
        gt_labels: ``(G,)`` ground-truth class ids.

    Returns:
        The ``(detection_row, ground_truth_row)`` pairs, in the order the
        detections claimed them. Rows index ``dets`` and ``gt_boxes`` directly.

    Examples:
        >>> import torch
        >>> dets = torch.tensor([[0.0, 0.0, 2.0, 2.0, 0.9, 1.0]])
        >>> gt_boxes = torch.tensor([[0.0, 0.0, 2.0, 2.0]])
        >>> _match_pairs(dets, gt_boxes, torch.tensor([1]))
        [(0, 0)]
    """
    total = int(gt_boxes.shape[0])
    pairs: list[tuple[int, int]] = []
    if total == 0:
        return pairs
    kept_rows = (dets[:, 4] > _SCORE_FLOOR).nonzero(as_tuple=True)[0]
    keep = dets[kept_rows]
    iou = _box_iou(keep[:, :4], gt_boxes)  # (P, G)
    matched_gt = torch.zeros(total, dtype=torch.bool)
    for det_index in range(keep.shape[0]):
        available = (keep[det_index, 5] == gt_labels) & ~matched_gt & (iou[det_index] >= _IOU_THRESHOLD)
        if bool(available.any()):
            gt_index = int((iou[det_index] * available).argmax())
            matched_gt[gt_index] = True
            pairs.append((int(kept_rows[det_index]), gt_index))
            if len(pairs) == total:
                break
    return pairs


def _recall_counts(dets: Tensor, gt_boxes: Tensor, gt_labels: Tensor) -> tuple[int, int]:
    """Count how many of one image's ground truths a detection claimed.

    Args:
        dets: ``(N, 6)`` A9 detections for one image, sorted by descending score.
        gt_boxes: ``(G, 4)`` ground-truth ``xyxy`` boxes.
        gt_labels: ``(G,)`` ground-truth class ids.

    Returns:
        A ``(matched, total)`` pair: matched ground truths and total ground truths.

    Examples:
        >>> import torch
        >>> dets = torch.tensor([[0.0, 0.0, 2.0, 2.0, 0.9, 1.0]])
        >>> gt_boxes = torch.tensor([[0.0, 0.0, 2.0, 2.0]])
        >>> _recall_counts(dets, gt_boxes, torch.tensor([1]))
        (1, 1)
    """
    return len(_match_pairs(dets, gt_boxes, gt_labels)), int(gt_boxes.shape[0])


def _anchor_grid(device: torch.device) -> tuple[Tensor, Tensor]:
    """Return the ``(anchor_points, strides)`` grid for the fixed image size on ``device``."""
    feature_sizes = [(_IMG_SIZE // stride, _IMG_SIZE // stride) for stride in _STRIDES]
    points, strides = make_anchor_points(feature_sizes, list(_STRIDES))
    return points.to(device), strides.to(device)


def evaluate_recall(module: DetectionLitModule, datamodule: DetectionDataModule) -> tuple[float, int]:
    """Measure train-set recall at IoU 0.5 over the letterbox-only slice.

    Runs the trained module over the val loader (the same 100 images with only the
    letterbox transform — no augmentation), decodes the one-to-one branch through
    the NMS-free :class:`~lucid_yolo.decode.topk_e2e.TopKDecoder`, and greedily matches
    every ground truth to a same-class detection (see :func:`_recall_counts`).

    Args:
        module: The trained detection module.
        datamodule: The datamodule whose val loader yields the letterboxed slice.

    Returns:
        A ``(recall, total_instances)`` pair: the matched fraction over all ground
        truths and the total ground-truth count.

    Examples:
        >>> evaluate_recall(module, datamodule)  # doctest: +SKIP
        (1.0, 592)
    """
    device = module.device
    module.eval()
    decoder = TopKDecoder(k=_MAX_DET)
    anchor_points, strides = _anchor_grid(device)
    matched_total = 0
    instance_total = 0
    with torch.no_grad():
        for batch in datamodule.val_dataloader():
            images, targets, _ = datamodule.on_after_batch_transfer(batch, 0)
            head_out: DualHeadOutput = module(images.to(device))
            dets = decoder(head_out.o2o_cls, head_out.o2o_box, anchor_points, strides).cpu()
            for image_dets, target in zip(dets, targets, strict=True):
                matched, total = _recall_counts(image_dets, target.boxes, target.labels)
                matched_total += matched
                instance_total += total
    recall = matched_total / instance_total if instance_total else 0.0
    return recall, instance_total


def _binary_iou(predicted: Tensor, target: Tensor) -> float:
    """Intersection over union of two boolean masks; zero when both are empty.

    Args:
        predicted: Boolean mask of any shape.
        target: Boolean mask of the same shape.

    Returns:
        The IoU as a float, or ``0.0`` when the union is empty (two empty masks
        agree perfectly but carry no evidence that the model found the instance).

    Examples:
        >>> import torch
        >>> a = torch.tensor([[True, True], [False, False]])
        >>> b = torch.tensor([[True, False], [False, False]])
        >>> _binary_iou(a, b)
        0.5
    """
    intersection = float((predicted & target).sum())
    union = float((predicted | target).sum())
    return intersection / union if union > 0 else 0.0


def _mask_iou_sum(dets: Tensor, pred_masks: Tensor, target: Targets) -> tuple[float, int]:
    """Total mask IoU of one image's ground truths, and how many there are.

    The ground truths are matched to detections by :func:`_match_pairs` — the same
    greedy box rule the recall gate uses — and each matched pair contributes its
    binary mask IoU. An **unmatched** ground truth contributes nothing to the sum
    while still counting in the total, so the mean over the returned counts scores
    a missed instance as a zero rather than excusing it.

    Args:
        dets: ``(N, 6)`` A9 detections for one image, sorted by descending score.
        pred_masks: ``(N, H, W)`` boolean decoded masks, row-aligned with ``dets``.
        target: The image's ground truth; its polygons are rasterised on the same
            letterboxed canvas the masks were decoded onto.

    Returns:
        A ``(iou_sum, num_instances)`` pair.

    Examples:
        >>> import torch
        >>> from lucid_yolo.data.targets import Targets
        >>> ring = torch.tensor([[0.0, 0.0], [2.0, 0.0], [2.0, 2.0], [0.0, 2.0]])
        >>> target = Targets(boxes=torch.tensor([[0.0, 0.0, 2.0, 2.0]]), labels=torch.tensor([1]), polygons=[ring])
        >>> dets = torch.tensor([[0.0, 0.0, 2.0, 2.0, 0.9, 1.0]])
        >>> masks = torch.zeros(1, _IMG_SIZE, _IMG_SIZE, dtype=torch.bool)
        >>> masks[0, :2, :2] = True
        >>> _mask_iou_sum(dets, masks, target)
        (1.0, 1)
    """
    total = int(target.boxes.shape[0])
    if total == 0:
        return 0.0, 0
    gt_masks = rasterize_polygons([ring.cpu() for ring in target.polygons], _IMG_SIZE, _IMG_SIZE)
    pairs = _match_pairs(dets, target.boxes, target.labels)
    iou_sum = sum(_binary_iou(pred_masks[det_row], gt_masks[gt_row]) for det_row, gt_row in pairs)
    return iou_sum, total


def evaluate_mask_iou(module: DetectionLitModule, datamodule: DetectionDataModule) -> tuple[float, int]:
    """Measure the train-set mean instance-mask IoU over the letterbox-only slice.

    Runs the trained module over the val loader (the same 100 images with only the
    letterbox transform) through the **deployed** segmentation path: the one-to-one
    branch's boxes and coefficients paired by
    :func:`~lucid_yolo.models.heads.detect.o2o_topk_with_indices`, then assembled,
    upsampled, box-cropped and binarized by
    :func:`~lucid_yolo.eval.segment_decode.decode_instance_masks` (A37). Masks are
    decoded one image at a time: every kept detection materializes a full-canvas
    float map, and the whole batch at once is a needless memory spike.

    Args:
        module: The trained ``task="segment"`` module.
        datamodule: The datamodule whose val loader yields the letterboxed slice.

    Returns:
        A ``(mask_iou, total_instances)`` pair: the mean IoU over **all** ground
        truths (unmatched ones scoring zero) and the total ground-truth count.

    Examples:
        >>> evaluate_mask_iou(module, datamodule)  # doctest: +SKIP
        (0.82, 592)
    """
    device = module.device
    module.eval()
    anchor_points, strides = _anchor_grid(device)
    iou_total = 0.0
    instance_total = 0
    with torch.no_grad():
        for batch in datamodule.val_dataloader():
            images, targets, _ = datamodule.on_after_batch_transfer(batch, 0)
            seg_out = module.forward_segmentation(images.to(device))
            coefficients = seg_out.detect.o2o_coeff
            assert coefficients is not None  # a "segment" module always builds the coefficient stems
            boxes = decode_ltrb(seg_out.detect.o2o_box, anchor_points, strides)
            dets, anchor_index = o2o_topk_with_indices(seg_out.detect.o2o_cls, boxes, k=_SEG_MAX_DET)
            gather_index = anchor_index.unsqueeze(-1).expand(-1, -1, coefficients.shape[-1])
            kept_coefficients = coefficients.gather(1, gather_index)
            for index, target in enumerate(targets):
                masks = decode_instance_masks(
                    seg_out.prototypes[index : index + 1],
                    kept_coefficients[index : index + 1],
                    dets[index : index + 1, :, :_BOX_COLUMNS],
                    image_size=(_IMG_SIZE, _IMG_SIZE),
                    threshold=_MASK_THRESHOLD,
                )
                iou_sum, count = _mask_iou_sum(dets[index].cpu(), masks[0].cpu(), target)
                iou_total += iou_sum
                instance_total += count
    return (iou_total / instance_total if instance_total else 0.0), instance_total


def evaluate_rotated_map50(module: DetectionLitModule, datamodule: DetectionDataModule) -> tuple[float, int]:
    """Measure the train-set rotated mAP50 over the letterbox-only slice (WP-088).

    Runs the trained module over the val loader (the same 100 images with only the
    letterbox transform) through the **deployed** oriented path:
    :func:`~lucid_yolo.models.heads.obb.decode_rboxes` assembles the one-to-one
    branch's boxes (A44) and :func:`~lucid_yolo.models.heads.obb.o2o_rotated_topk`
    ranks them, gathering each angle by the anchor its own box was ranked by. Scoring
    is WP-063's protocol (:func:`~lucid_yolo.eval.dota_eval.evaluate_rotated_map`),
    with the R18 difficult flags taken from the targets rather than defaulted (A48).

    Scoring runs in letterbox coordinates: a letterbox is one isotropic scale plus a
    translation, and rotated IoU is a ratio of areas, so mapping both sides back
    through :func:`~lucid_yolo.decode.common.rboxes_to_letterboxed_original` would
    divide the same number by itself.

    Args:
        module: The trained ``task="obb"`` module.
        datamodule: The datamodule whose val loader yields the letterboxed slice.

    Returns:
        A ``(rotated_map50, total_instances)`` pair.

    Examples:
        >>> evaluate_rotated_map50(module, datamodule)  # doctest: +SKIP
        (0.93, 592)
    """
    device = module.device
    module.eval()
    anchor_points, strides = _anchor_grid(device)
    preds: list[dict[str, Tensor]] = []
    ground_truth: list[dict[str, Tensor]] = []
    with torch.no_grad():
        for batch in datamodule.val_dataloader():
            images, targets, _ = datamodule.on_after_batch_transfer(batch, 0)
            head_out: DualHeadOutput = module(images.to(device))
            assert head_out.o2o_angle is not None  # an "obb" module always builds the angle stems
            rboxes = decode_rboxes(head_out.o2o_box, head_out.o2o_angle, anchor_points, strides)
            detections = o2o_rotated_topk(head_out.o2o_cls, rboxes, k=MAX_DETECTIONS)
            preds.extend(rotated_detections_to_predictions(detections))
            ground_truth.extend(
                {
                    "rboxes": target.rboxes.cpu(),
                    "labels": target.labels.cpu().to(torch.long),
                    "difficult": target.difficult.cpu(),
                }
                for target in targets
            )
    instances = sum(int(entry["rboxes"].shape[0]) for entry in ground_truth)
    return evaluate_rotated_map(preds, ground_truth)["map_50"], instances


@dataclass(frozen=True)
class TaskSpec:
    """Everything that differs between the three overfit gates.

    Attributes:
        module_task: The :class:`~lucid_yolo.ptl.module.DetectionLitModule` task.
        metric: Key the achieved score is reported and frozen under.
        label: Human-readable metric name for the console line.
        floor: Acceptance floor the score must clear.
        tolerance: Golden tolerance on the score.
        golden_path: Where ``--freeze`` writes the golden.
        producer: Producer spec recorded inside the golden file.
        scorer: Callable measuring the trained module over the val loader.
        generator_task: The ``fuse-augmentations`` task the slice is generated with.
        slice_dir: Where that slice is cached; one directory per annotation shape.
    """

    module_task: str
    metric: str
    label: str
    floor: float
    tolerance: float
    golden_path: Path
    producer: str
    scorer: Callable[[DetectionLitModule, DetectionDataModule], tuple[float, int]]
    generator_task: str = "segmentation"
    slice_dir: Path = _SLICE_DIR


#: The two wired gates, keyed by the ``--task`` value.
TASK_SPECS: dict[str, TaskSpec] = {
    "det": TaskSpec(
        module_task="detect",
        metric="train_recall_at_050",
        label="recall@0.5",
        floor=_RECALL_FLOOR,
        tolerance=_RECALL_TOL,
        golden_path=_GOLDEN_PATH,
        producer=_PRODUCER_SPEC,
        scorer=evaluate_recall,
    ),
    "seg": TaskSpec(
        module_task="segment",
        metric="train_mask_iou",
        label="mask IoU",
        floor=_MASK_IOU_FLOOR,
        tolerance=_MASK_IOU_TOL,
        golden_path=_SEG_GOLDEN_PATH,
        producer=_SEG_PRODUCER_SPEC,
        scorer=evaluate_mask_iou,
    ),
    "obb": TaskSpec(
        module_task="obb",
        metric="train_rotated_map50",
        label="rotated mAP50",
        floor=_ROTATED_MAP50_FLOOR,
        tolerance=_ROTATED_MAP50_TOL,
        golden_path=_OBB_GOLDEN_PATH,
        producer=_OBB_PRODUCER_SPEC,
        scorer=evaluate_rotated_map50,
        generator_task="obb",
        slice_dir=_OBB_SLICE_DIR,
    ),
}


def _train_and_score(recipe: Recipe, split: Path, deterministic: bool, spec: TaskSpec) -> tuple[float, int, int]:
    """Build, train, and score one overfit run; return ``(score, instances, classes)``."""
    seed_everything(recipe.seed, workers=True)
    num_classes = _num_classes(split)
    module = build_module(recipe, num_classes, module_task=spec.module_task)
    datamodule = build_datamodule(
        split,
        recipe,
        mask_targets=spec.module_task == "segment",
        rotated_targets=spec.module_task == "obb",
    )
    _make_trainer(recipe, deterministic).fit(module, datamodule=datamodule)
    score, instances = spec.scorer(module, datamodule)
    return score, instances, num_classes


def run_overfit(task: str = "det") -> dict[str, float]:
    """Run the full overfit pipeline for one task and return the golden metric mapping.

    Generates the slice, trains the ``n``-scale module end to end (attempting
    deterministic execution, falling back to non-deterministic if the accelerator
    lacks a deterministic kernel — expected on MPS), then scores it with the task's
    gate metric. Every value is produced by *running* the pipeline, never
    hand-written.

    Args:
        task: ``"det"`` (train recall at IoU 0.5) or ``"seg"`` (mean train mask
            IoU). Defaults to ``"det"``.

    Returns:
        A mapping of the frozen metrics: ``num_images``, ``num_instances``,
        ``num_classes``, ``epochs``, ``img_size`` (all integer-valued) and the
        task's own metric key.

    Raises:
        KeyError: If ``task`` is not one of the wired gates.

    Examples:
        >>> metrics = run_overfit()  # doctest: +SKIP
        >>> metrics["train_recall_at_050"] >= 0.95  # doctest: +SKIP
        True
    """
    spec = TASK_SPECS[task]
    recipe = load_recipe()
    split = generate_slice(spec.slice_dir, spec.generator_task)
    try:
        score, instances, num_classes = _train_and_score(recipe, split, True, spec)
    except RuntimeError:
        score, instances, num_classes = _train_and_score(recipe, split, False, spec)
    return {
        "num_images": float(_NUM_IMAGES),
        "num_instances": float(instances),
        "num_classes": float(num_classes),
        "epochs": float(recipe.max_epochs),
        "img_size": float(_IMG_SIZE),
        spec.metric: round(score, 6),
    }


def overfit_micro_det() -> dict[str, float]:
    """Golden producer: the overfit-100 detection metrics (WP-040).

    A zero-argument producer for the golden harness. Recomputing it retrains the
    slice from scratch on the local accelerator, so it is excluded from the default
    offline harness (the golden lives under ``goldens/gpu/``) and checked only under
    ``scripts/check_goldens.py --include-gpu``.

    Returns:
        The metric mapping from :func:`run_overfit`.

    Examples:
        >>> metrics = overfit_micro_det()  # doctest: +SKIP
        >>> sorted(metrics)  # doctest: +SKIP
        ['epochs', 'img_size', 'num_classes', 'num_images', 'num_instances', 'train_recall_at_050']
    """
    return run_overfit("det")


def overfit_micro_obb() -> dict[str, float]:
    """Golden producer: the overfit-100 oriented metrics (WP-088).

    The oriented counterpart of :func:`overfit_micro_det`, with the same
    accelerator-only status: it retrains the slice from scratch, so its golden lives
    under ``goldens/gpu/`` and the default offline harness never recomputes it.

    Returns:
        The metric mapping from :func:`run_overfit`.

    Examples:
        >>> metrics = overfit_micro_obb()  # doctest: +SKIP
        >>> sorted(metrics)  # doctest: +SKIP
        ['epochs', 'img_size', 'num_classes', 'num_images', 'num_instances', 'train_rotated_map50']
    """
    return run_overfit("obb")


def overfit_micro_seg() -> dict[str, float]:
    """Golden producer: the overfit-100 segmentation metrics (WP-087).

    The segmentation counterpart of :func:`overfit_micro_det`, with the same
    accelerator-only status: it retrains the slice from scratch, so its golden
    lives under ``goldens/gpu/`` and the default offline harness never recomputes it.

    Returns:
        The metric mapping from :func:`run_overfit`.

    Examples:
        >>> metrics = overfit_micro_seg()  # doctest: +SKIP
        >>> sorted(metrics)  # doctest: +SKIP
        ['epochs', 'img_size', 'num_classes', 'num_images', 'num_instances', 'train_mask_iou']
    """
    return run_overfit("seg")


def write_golden(metrics: dict[str, float], spec: TaskSpec = TASK_SPECS["det"]) -> None:
    """Freeze ``metrics`` into the task's golden JSON with its tolerance pinned.

    Args:
        metrics: The metric mapping to store as the golden's ``values``.
        spec: The task whose golden path, producer and tolerance are used.
            Defaults to the detection gate.

    Examples:
        >>> write_golden(run_overfit())  # doctest: +SKIP
    """
    spec.golden_path.parent.mkdir(parents=True, exist_ok=True)
    golden = {
        "producer": spec.producer,
        "tolerances": {spec.metric: spec.tolerance},
        "values": metrics,
    }
    spec.golden_path.write_text(json.dumps(golden, indent=2) + "\n")


def main(argv: list[str] | None = None) -> int:
    """Run the overfit gate for one task and optionally freeze its golden.

    Args:
        argv: Command-line arguments (defaults to ``sys.argv[1:]``).

    Returns:
        ``0`` when the task's score clears its floor; ``1`` otherwise (or when an
        unsupported task is requested).
    """
    parser = argparse.ArgumentParser(description="Overfit a fixed ~100-image slice and gate on a train metric.")
    parser.add_argument(
        "--task", default="det", help="gate to run: 'det' (recall), 'seg' (mask IoU) or 'obb' (rotated mAP50)"
    )
    parser.add_argument("--freeze", action="store_true", help="write the task's goldens/gpu/ file on success")
    args = parser.parse_args(argv)

    spec = TASK_SPECS.get(args.task)
    if spec is None:
        print(f"unsupported task {args.task!r}; wired tasks are {sorted(TASK_SPECS)}")
        return 1

    metrics = run_overfit(args.task)
    score = metrics[spec.metric]
    print(f"overfit-{args.task}: {spec.label} = {score:.4f} over {int(metrics['num_instances'])} instances")
    if score < spec.floor:
        print(f"FAIL: {spec.label} {score:.4f} below floor {spec.floor}")
        return 1
    if args.freeze:
        write_golden(metrics, spec)
        print(f"froze golden -> {spec.golden_path.relative_to(REPO_ROOT)}")
    print(f"PASS: {spec.label} {score:.4f} >= {spec.floor}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
