# SPDX-License-Identifier: Apache-2.0
"""Unit gate for the synthetic fixture cache's invalidation key (M-45).

``tests/fixtures/synthetic.py`` caches its generated micro-datasets on disk, and what that
cache is keyed on decides whether a warm machine and a cold CI runner are looking at the
same scene. Keyed on the annotation file merely existing, they were not: a changed seed,
image count, shape set or pinned ``fuse-augmentations`` commit produced a new scene on CI
(always cold, the directory is gitignored) while every fixture-consuming test on a
contributor's machine kept running against the previous one, silently. These tests pin the
fingerprint key instead: a changed generation request regenerates, an unchanged one is
served without touching the generator, and ``make clean`` removes the cache directory.

Every set here is generated into ``tmp_path``, never the shared session cache.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
import synthetic

_SPLIT = "train"
_ANNOTATION = "_annotations.coco.json"
#: A seed that is simply not any of the three the module ships, so a regeneration shows.
_OTHER_SEED = 19700101
#: Repository root, three levels up from ``tests/fixtures/test_synthetic.py``.
_REPO_ROOT = Path(__file__).resolve().parents[2]


def _annotation_bytes(dataset_dir: Path) -> bytes:
    """Return the raw COCO annotation document of a generated set.

    Args:
        dataset_dir: A directory returned by one of the ``generate_*_fixtures`` helpers.

    Returns:
        The bytes of the ``train`` split's ``_annotations.coco.json``.

    Examples:
        >>> import tempfile
        >>> with tempfile.TemporaryDirectory() as tmp:
        ...     len(_annotation_bytes(synthetic.generate_obb_fixtures(Path(tmp)))) > 0
        True
    """
    return (dataset_dir / _SPLIT / _ANNOTATION).read_bytes()


class TestFixtureCacheKey:
    """The cache is keyed on the generation request, not on the annotation file existing."""

    def test_a_changed_seed_regenerates_the_set(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        """Changing a seed replaces the cached scene instead of serving the previous one.

        This is the M-45 failure exactly: the seed constants are edited in the source, and
        every machine that has generated once before keeps the old images and annotations
        because the annotation file still exists. CI, which is always cold, sees the new
        ones — so the two disagree about what every fixture-consuming test is asserting
        against, and nothing says so.
        """
        before = _annotation_bytes(synthetic.generate_detseg_fixtures(tmp_path))
        monkeypatch.setattr(synthetic, "DETSEG_SEED", _OTHER_SEED)

        after = _annotation_bytes(synthetic.generate_detseg_fixtures(tmp_path))

        assert after != before, "a changed seed served the previously cached scene"

    def test_a_changed_image_count_regenerates_the_set(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        """Changing the image count replaces the cached scene, leaving no surplus images behind.

        Shrinking the set is the case a fingerprint check alone would not fix: regenerating
        into a directory that still holds the larger previous run leaves the extra images on
        disk, and a reader that walks the split directory rather than the annotation file
        would then see images the document never declares.
        """
        synthetic.generate_obb_fixtures(tmp_path)
        monkeypatch.setattr(synthetic, "OBB_NUM_IMAGES", synthetic.OBB_NUM_IMAGES - 1)

        dataset_dir = synthetic.generate_obb_fixtures(tmp_path)

        images = sorted((dataset_dir / _SPLIT).glob("*.jpg"))
        assert len(images) == synthetic.OBB_NUM_IMAGES

    def test_an_unchanged_request_is_served_from_the_cache(
        self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
    ) -> None:
        """An identical second call returns without invoking the generator at all.

        The cache still has to *be* a cache: the fixture suite generates once per session
        and every consumer after that pays nothing. A fingerprint that matched only on a
        fresh run would turn every session into a full regeneration.
        """
        first = synthetic.generate_keypoints_fixtures(tmp_path)
        monkeypatch.setattr(synthetic, "generate_dataset", _refuse_to_generate)

        second = synthetic.generate_keypoints_fixtures(tmp_path)

        assert second == first

    def test_a_missing_fingerprint_regenerates_the_set(self, tmp_path: Path) -> None:
        """A set cached before fingerprints existed is refreshed once rather than trusted.

        Every warm machine at the time of this change holds exactly that: a complete set
        with no fingerprint beside it, generated by a request nothing recorded. Treating the
        absent key as a match would leave those machines on the stale scene indefinitely.
        """
        dataset_dir = synthetic.generate_detseg_fixtures(tmp_path)
        (dataset_dir / synthetic._FINGERPRINT_NAME).unlink()

        synthetic.generate_detseg_fixtures(tmp_path)

        assert (dataset_dir / synthetic._FINGERPRINT_NAME).is_file()

    def test_the_pinned_generator_commit_is_part_of_the_key(self) -> None:
        """The fingerprint names the exact upstream commit, not just its version string.

        ``fuse-augmentations`` is pinned to a git SHA and reports a dev version that does
        not move when that SHA does, so a bump to a generator that draws different scenes
        would leave the version identical and every cached set silently stale.
        """
        identity = synthetic._generator_identity()

        assert "direct_url" in identity, "a git-pinned generator must contribute its commit to the key"
        assert "commit_id" in identity["direct_url"]


def _refuse_to_generate(*_args: object, **_kwargs: object) -> None:
    """A ``generate_dataset`` replacement asserting the cache was consulted first.

    Examples:
        >>> try:
        ...     _refuse_to_generate()
        ... except AssertionError as exc:
        ...     str(exc)
        'the fixture cache regenerated a set whose fingerprint already matched'
    """
    raise AssertionError("the fixture cache regenerated a set whose fingerprint already matched")


def test_make_clean_removes_the_generated_fixture_cache() -> None:
    """``make clean`` clears ``tests/fixtures/_generated`` along with the other caches.

    The directory is gitignored, so it survives every checkout and every branch switch; a
    ``clean`` that left it in place meant "start from nothing" named two different states
    depending on whether the machine had ever run the suite.
    """
    recipe = subprocess.run(
        ["make", "--dry-run", "--no-print-directory", "clean"],
        capture_output=True,
        text=True,
        cwd=_REPO_ROOT,
        check=True,
    ).stdout

    assert "tests/fixtures/_generated" in recipe
