# SPDX-License-Identifier: Apache-2.0
"""Developer Certificate of Origin sign-off validator (WP-142).

Layer one of the three admission layers ``docs/CONTRIBUTING.md`` describes. Every
non-merge commit in a pull request must carry a well-formed ``Signed-off-by:``
trailer naming a person and an address that reaches them, which is the
contributor's own representation that they wrote the patch or have the right to
pass it on.

This is deliberately a file in this repository rather than a hosted app. The check
is part of what a reviewer can read, it runs identically on a laptop and in CI, and
it survives whatever happens to a third-party service — which is the same reasoning
that keeps the commit-trailer contract local.

**What it does not check, on purpose.** It does not require a sign-off address to
match the commit author's. A DCO sign-off is a *representation by the signer*, not
an identity proof: co-authored work legitimately carries several, an author
committing under an employer address may sign under a personal one, and a
maintainer applying a contributor's patch signs their own line beside the original.
Requiring a match would reject all three while catching nobody who is willing to
type a false name — so the check enforces the shape of the statement and leaves its
truth where the DCO itself puts it, with the person who signed.

Examples:
    Validate a single message file (exit 1 on any violation)::

        python scripts/lint/check_dco.py --file .git/COMMIT_EDITMSG

    Validate every non-merge commit in a range::

        python scripts/lint/check_dco.py --range origin/main..HEAD
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

#: The repository this checker belongs to, resolved from the file rather than from the
#: process, so both ``git`` calls below read this repository's history whatever directory
#: the checker was launched from. ``release_guard.py`` already anchors this way.
REPO_ROOT = Path(__file__).resolve().parents[2]

#: A sign-off trailer: a display name, then an address in angle brackets. The name is
#: required to hold a non-space character so ``Signed-off-by: <a@b.c>`` is refused --
#: an address alone is not the "real name" the DCO asks for. The address is checked for
#: shape only (a local part, an ``@``, a dotted domain): validating deliverability is
#: neither possible here nor what the trailer is for.
SIGNOFF_RE = re.compile(
    r"^Signed-off-by: *(?P<name>\S[^<>]*?) *<(?P<email>[^@<>\s]+@[^@<>\s]+\.[^@<>\s]+)>\s*$",
    re.MULTILINE,
)

#: A line that means to be a sign-off and is not one. Matched case-insensitively and
#: against common misspellings so the report can say "malformed" rather than "missing",
#: which is the difference between a one-character fix and a confused contributor.
NEAR_MISS_RE = re.compile(r"^\s*signed[- ]?off[- ]?by\s*:?.*$", re.MULTILINE | re.IGNORECASE)


def validate_message(message: str) -> list[str]:
    """Return the sign-off violations in one commit message.

    Args:
        message: The full commit message, subject and body.

    Returns:
        Violation strings; empty when the message carries a valid sign-off.

    Examples:
        ```pycon
        >>> validate_message("fix: x\\n\\nSigned-off-by: Ada Lovelace <ada@example.com>\\n")
        []
        >>> validate_message("fix: x\\n")
        ["missing 'Signed-off-by:' trailer (git commit -s adds one)"]
        >>> validate_message("fix: x\\n\\nSigned-off-by: Ada\\n")[0].startswith('malformed')
        True

        ```
    """
    if SIGNOFF_RE.search(message):
        return []
    near = NEAR_MISS_RE.search(message)
    if near:
        return [f"malformed sign-off {near.group(0).strip()!r}; expected 'Signed-off-by: Real Name <address>'"]
    return ["missing 'Signed-off-by:' trailer (git commit -s adds one)"]


def _commit_shas(commit_range: str) -> list[str]:
    """Return the non-merge commit hashes in a git range, newest first.

    Merges are excluded because their message is generated by whoever pressed the
    button rather than written by the contributor, so there is no representation in
    it to check.

    Args:
        commit_range: A git range expression such as ``origin/main..HEAD``.

    Returns:
        Full commit hashes; empty when the range selects nothing.
    """
    result = subprocess.run(
        ["git", "log", "--no-merges", "--format=%H", commit_range],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def _commit_message(sha: str) -> str:
    """Return the full message of one commit.

    Args:
        sha: The commit hash to read.

    Returns:
        Subject and body as one string.
    """
    result = subprocess.run(
        ["git", "log", "-1", "--format=%B", sha],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _report(reports: list[tuple[str, list[str]]]) -> int:
    """Print per-commit results and return the process exit code.

    An empty range is reported as clean rather than as an error: a pull request that
    selects no commit is not a pull request that failed to sign one.

    Args:
        reports: ``(label, violations)`` pairs, one per validated message.

    Returns:
        ``1`` when any message has violations, otherwise ``0``.
    """
    failed = [(label, violations) for label, violations in reports if violations]
    for label, violations in failed:
        print(f"COMMIT {label}: FAIL")
        for item in violations:
            print(f"  - {item}")
    if failed:
        print(f"DCO check FAILED: {len(failed)} of {len(reports)} commit(s) unsigned")
        print("Fix: git rebase --signoff <base>, or amend each commit with 'git commit -s --amend'")
        return 1
    print(f"DCO check clean: {len(reports)} commit(s) signed off")
    return 0


def main(argv: list[str] | None = None) -> int:
    """Parse arguments, validate the selected message(s), and print a report.

    Args:
        argv: Command-line arguments; ``None`` uses ``sys.argv``.

    Returns:
        Process exit code: ``0`` clean, ``1`` on any violation.

    Examples:
        Command-line usage (exit status is the process return code)::

            $ python scripts/lint/check_dco.py --file .git/COMMIT_EDITMSG
            $ python scripts/lint/check_dco.py --range origin/main..HEAD
    """
    parser = argparse.ArgumentParser(description="Validate Developer Certificate of Origin sign-offs.")
    target = parser.add_mutually_exclusive_group(required=True)
    target.add_argument("--file", type=Path, help="validate a single commit-message file")
    target.add_argument("--range", dest="commit_range", help="validate every non-merge commit in a git range")
    args = parser.parse_args(argv)

    reports: list[tuple[str, list[str]]] = []
    if args.file is not None:
        reports.append((str(args.file), validate_message(args.file.read_text(encoding="utf-8"))))
    else:
        reports.extend((sha[:12], validate_message(_commit_message(sha))) for sha in _commit_shas(args.commit_range))
    return _report(reports)


if __name__ == "__main__":
    sys.exit(main())
